services:
  - type: web
    name: moviesnation-scrape
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn Moviesnation_scrape.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: RAPIDAPI_KEY
        sync: false
      - key: RAPIDAPI_HOST
        value: imdb236.p.rapidapi.com
